# Generated by Django 5.2.7 on 2025-11-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Approved'), ('2', 'Disapproved')], default='0', max_length=1),
        ),
    ]
